version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
   - x64
   #- x86

clone_depth: 5

environment:
  matrix:
    - subset: sse
    - subset: avx
    - subset: avx512
    - subset: neon

install:
- cmd: git submodule update --init --recursive

build_script:
- cmd: >-
    CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=%PLATFORM% -host_arch=%PLATFORM% -no_logo

    ctest -VV -S C:\projects\vc\scripts\test.cmake
