language: cpp

cache:
    ccache: true
    directories:
        - $HOME/.cache/sde

env:
    - arch=x86_64  subset=sse    VcSkipTests=loadstore
    - arch=x86_64  subset=avx    VcSkipTests=loadstore
    - arch=x86_64  subset=avx2   VcSkipTests=loadstore
    - arch=x86_64  subset=avx512 VcSkipTests=loadstore
    - arch=aarch64 subset=neon   VcSkipTests=loadstore

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

# The whitespace in "env:" lines must match the definition above!
matrix:
  exclude:
    - env: arch=x86_64  subset=avx512
      os: osx
    - env: arch=aarch64 subset=neon
      os: osx
  allow_failures:
    - env: arch=aarch64 subset=neon

# The following gives us Ubuntu 14.04 LTS instead of 12.04 LTS
sudo: required
dist: trusty

install:
    - case "$TRAVIS_OS_NAME-$CXX-$arch" in
        linux-g++-x86_64)
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial main' &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial-updates main' &&
          sudo apt-get update -q &&
          sudo apt-get install g++-6 binutils -y &&
          export CXX=g++-6 CC=gcc-6;;
        linux-clang++-x86_64)
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
          sudo apt-get update -q &&
          sudo apt-get install clang-3.8 libstdc++-6-dev &&
          export CXX=clang++-3.8 CC=clang-3.8;;
        osx-g++-x86_64)
          brew update &&
          brew install gcc6 &&
          export CXX=g++-7 CC=gcc-7;;
        osx-clang++-x86_64)
          brew update &&
          brew install llvm &&
          export CXX=/usr/local/opt/llvm/bin/clang++ CC=/usr/local/opt/llvm/bin/clang &&
          export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib" &&
          export CPPFLAGS=-I/usr/local/opt/llvm/include;;
        linux-g++-aarch64)
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial main' &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial-updates main' &&
          sudo apt-get update -q &&
          sudo apt-get install -y g++-5-aarch64-linux-gnu &&
          export CXX=aarch64-linux-gnu-g++-5 CC=aarch64-linux-gnu-gcc-5 CMAKE_TOOLCHAIN_FILE=cmake/toolchain-arm-linux.cmake;;
        linux-clang++-aarch64)
          sudo apt-get install -y clang-3.8 &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial main' &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial-updates main' &&
          sudo apt-get update -q &&
          sudo apt-get install -y libstdc++-5-dev-arm64-cross gcc-5-aarch64-linux-gnu &&
          export CPATH=/usr/aarch64-linux-gnu/include &&
          export CXX="clang++-3.8 -target aarch64-linux-gnu" CC="clang-3.8 -target aarch64-linux-gnu" &&
          export CMAKE_TOOLCHAIN_FILE=cmake/toolchain-arm-linux.cmake;;
      esac

before_script:
    # ptrace_scope=0 is required on Ubuntu for SDE to work
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope;
      fi
    - $CXX --version
    - cmake --version
    - export dashboard_model=Experimental
    - export build_type=Release
    - export NUMBER_OF_PROCESSORS=2

script:
    - ctest -VV -S scripts/test.cmake

notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net##Vc"
        on_success: change # [always|never|change] # default: always
        on_failure: always # [always|never|change] # default: always
        use_notice: true
        skip_join: true
